package fr.openwide.alfresco.repo.wsgenerator.processor;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.Name;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.MirroredTypeException;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;

import fr.openwide.alfresco.repo.wsgenerator.annotation.BootstrapView;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateBootstrapModel;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateCron;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GeneratePatch;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateService;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateWebScript;
import fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateWebScript.GenerateWebScriptLifecycle;
import fr.openwide.alfresco.repo.wsgenerator.annotation.WebScriptEndPoint;
import fr.openwide.alfresco.repo.wsgenerator.model.WebScriptParam;

@SupportedSourceVersion(SourceVersion.RELEASE_8)
@SupportedAnnotationTypes({
	"fr.openwide.alfresco.repo.wsgenerator.annotation.WebScriptEndPoint",
	"fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateWebScript",
	"fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateService",
	"fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateBootstrapModel",
	"fr.openwide.alfresco.repo.wsgenerator.annotation.GeneratePatch",
	"fr.openwide.alfresco.repo.wsgenerator.annotation.GenerateCron",
})
public class GenerateWebScriptAnnotationProcessor extends AbstractProcessor {

	// On écrit dans /tmp les URL, car le build peut se faire en deux fois
	private File API_FOLDER = new File(System.getProperty("java.io.tmpdir"), getClass().getName());

	private XMLStreamWriter springContextXml = null;
	
	@Override
	public synchronized void init(ProcessingEnvironment processingEnv) {
		super.init(processingEnv);
		
		if (springContextXml != null) {
			throw new IllegalStateException("Init déjà appelé");
		}
		
		Filer filer = processingEnv.getFiler();
		try {
			FileObject fileObject = filer.createResource(StandardLocation.CLASS_OUTPUT, 
					"alfresco.extension", "owsi-generator-context.xml");
			processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Génération de " + fileObject.toUri());
			
			Writer out = fileObject.openWriter();
			springContextXml = new IndentingXMLStreamWriter(XMLOutputFactory.newFactory().createXMLStreamWriter(out));
			springContextXml.writeStartDocument();
			springContextXml.writeComment("Generated by " + getClass());
			springContextXml.writeCharacters("\n");
			
			springContextXml.writeStartElement("beans");
			springContextXml.writeDefaultNamespace("http://www.springframework.org/schema/beans");
			springContextXml.writeNamespace("xsi", "http://www.w3.org/2001/XMLSchema-instance");
			springContextXml.writeAttribute("xsi", "http://www.w3.org/2001/XMLSchema-instance", "schemaLocation", 
					"http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd");
		} catch (IOException e) {
			throw new IllegalStateException(e);
		} catch (XMLStreamException e) {
			throw new IllegalStateException(e);
		}
	}
	
	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Process " + annotations.toString());
		
		try {
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(GenerateBootstrapModel.class)) {
				generateComment(annotatedClassElement);
				processBootstrapModel(annotatedClassElement);
			}
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(GeneratePatch.class)) {
				generateComment(annotatedClassElement);
				processPatch(annotatedClassElement);
			}
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(GenerateService.class)) {
				generateComment(annotatedClassElement);
				processService(annotatedClassElement);
			}
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(GenerateCron.class)) {
				generateComment(annotatedClassElement);
				processScheduledJob(annotatedClassElement);
			}
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(WebScriptEndPoint.class)) {
				generateComment(annotatedClassElement);
				processWsEndPoint(annotatedClassElement);
			}
			for (Element annotatedClassElement : roundEnv.getElementsAnnotatedWith(GenerateWebScript.class)) {
				generateComment(annotatedClassElement);
				processWs(annotatedClassElement);
			}
			
			if (roundEnv.processingOver()) {
				springContextXml.writeEndElement(); // beans
				springContextXml.writeEndDocument();
				springContextXml.flush();
				springContextXml.close();
				springContextXml = null;
				
				processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Génération terminée");
			}
		} catch (XMLStreamException e) {
			throw new IllegalStateException(e);
		}
		
		return true;
	}
	
	private void generateComment(Element annotatedClassElement) throws XMLStreamException {
		Name className = ((TypeElement) annotatedClassElement).getQualifiedName();
		springContextXml.writeCharacters("\n\n  ");
		springContextXml.writeComment("Generated for " + className);
	}

	private void processWsEndPoint(Element annotatedClassElement) {
		WebScriptEndPoint webScriptEndPoint = annotatedClassElement.getAnnotation(WebScriptEndPoint.class);
		
		API_FOLDER.mkdirs();
		File apiUrlFile = new File(API_FOLDER, getFullName(annotatedClassElement));
		try (PrintWriter out = new PrintWriter(new FileWriter(apiUrlFile))) {
			out.println(webScriptEndPoint.method().name());
			out.println(webScriptEndPoint.url());
			out.flush();
		} catch (IOException e) {
			throw new IllegalStateException(e);
		}
	}

	private void processWs(Element annotatedClassElement) throws XMLStreamException {
		GenerateWebScript generateWebScript = annotatedClassElement.getAnnotation(GenerateWebScript.class);
		Name className = ((TypeElement) annotatedClassElement).getQualifiedName();

		String[] urls = generateWebScript.url();
		String method = generateWebScript.method().name().toLowerCase();
		
		try {
			generateWebScript.paramClass();
		} catch( MirroredTypeException mte ) {
			String paramClass = mte.getTypeMirror().toString();
			if (! WebScriptParam.class.getName().equals(paramClass)) {
				if (urls.length != 0) {
					throw new IllegalStateException(getFullName(annotatedClassElement) + " : When declaring @GenerateWebScript.paramClass(), url shoud not be defined.");
				}
				if (! "get".equals(method)) {
					throw new IllegalStateException(getFullName(annotatedClassElement) + " : When declaring @GenerateWebScript.paramClass(), method shoud not be defined.");
				}
				File apiUrlFile = new File(API_FOLDER, paramClass);
				if (! apiUrlFile.canRead()) {
					throw new IllegalStateException(getFullName(annotatedClassElement) + " : When declaring @GenerateWebScript.paramClass(), API project should be build first.");
				}
				try (BufferedReader in = new BufferedReader(new FileReader(apiUrlFile))) {
					method = in.readLine().toLowerCase();
					urls = new String[] { in.readLine() };
				} catch (IOException e) {
					throw new IllegalStateException(e);
				}
			}
		}
		
		String firstUrl = (urls.length > 0) ? urls[0] : "";
		String wsFolder = (! generateWebScript.wsFolder().isEmpty()) ? generateWebScript.wsFolder() : StringUtils.substringBeforeLast(firstUrl, "/").replace('{', '_').replace('}', '_');
		String wsName = (! generateWebScript.wsName().isEmpty()) ? generateWebScript.wsName() : StringUtils.substringBefore(StringUtils.substringAfterLast(firstUrl, "/"), "?").replace(".", "-").replace('{', '_').replace('}', '_');

		String shortName = (! generateWebScript.shortName().isEmpty()) ? StringEscapeUtils.escapeXml10(generateWebScript.shortName()) : wsName;
		CharSequence description = (! generateWebScript.description().isEmpty()) ? StringEscapeUtils.escapeXml10(generateWebScript.description()) : className;

		String family = generateWebScript.family().isEmpty() 
				? ((firstUrl.split("/").length > 1) ? firstUrl.split("/")[1] : "root")
				: generateWebScript.family();
		String formatDefault = generateWebScript.formatDefault().isEmpty() 
				? generateWebScript.formatDefaultEnum().name().toLowerCase() 
				: generateWebScript.formatDefault();

		String[] urlsFinal = urls;
		generateXml(annotatedClassElement, 
				"alfresco.extension.templates.webscripts" + wsFolder.replace("/", "."), 
				wsName + "." + method + ".desc.xml", (xml) -> {
			xml.writeStartElement("webscript");
			xml.writeStartElement("shortname"); xml.writeCharacters(shortName); xml.writeEndElement();
			xml.writeStartElement("description"); xml.writeCharacters(description.toString()); xml.writeEndElement();

			for (String url : urlsFinal) {
				xml.writeStartElement("url"); xml.writeCharacters(url); xml.writeEndElement();
			}
			
			xml.writeStartElement("format"); 
			xml.writeAttribute("default", formatDefault);
			xml.writeCharacters(generateWebScript.format().name().toLowerCase()); 
			xml.writeEndElement();
			
			xml.writeStartElement("authentication"); xml.writeCharacters(generateWebScript.authentication().name().toLowerCase()); xml.writeEndElement();
			
			xml.writeStartElement("transaction"); 
			xml.writeAttribute("allow", generateWebScript.transactionAllow().name().toLowerCase());
			xml.writeCharacters(generateWebScript.transaction().name().toLowerCase());
			xml.writeEndElement();

			xml.writeStartElement("family"); xml.writeCharacters(family); xml.writeEndElement();
			
			if (   generateWebScript.cache().never() != true 
				|| generateWebScript.cache().isPublic() != false 
				|| generateWebScript.cache().mustrevalidate() != true) {
				xml.writeStartElement("cache");
				
				xml.writeStartElement("never");
				xml.writeCharacters(Boolean.toString(generateWebScript.cache().never()));
				xml.writeEndElement(); // never

				xml.writeStartElement("public");
				xml.writeCharacters(Boolean.toString(generateWebScript.cache().isPublic()));
				xml.writeEndElement(); // public

				xml.writeStartElement("mustrevalidate");
				xml.writeCharacters(Boolean.toString(generateWebScript.cache().mustrevalidate()));
				xml.writeEndElement(); // mustrevalidate

				xml.writeEndElement(); // cache
			}

			if (generateWebScript.lifecycle() != GenerateWebScriptLifecycle.DEFAULT) {
				xml.writeStartElement("lifecycle"); xml.writeCharacters(generateWebScript.lifecycle().name().toLowerCase()); xml.writeEndElement();
			}
			
			xml.writeEndElement(); // webscript
		});
		
		if (generateWebScript.useViewFile()) {
			try {
				Filer filer = processingEnv.getFiler();
				FileObject viewFile = filer.getResource(StandardLocation.CLASS_PATH, 
						"alfresco.extension.templates.webscripts" + wsFolder.replace("/", "."), 
						wsName + "." + method + "." + formatDefault + ".ftl");
				processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Le fichier " + viewFile.toUri() + " existe bien");
			} catch (FileNotFoundException ex) {
				throw new IllegalStateException("If you declare useViewFile=true, you must create a file "
						+ "src/main/resources/alfresco/extension/templates/webscripts" + wsFolder + "/" 
						+ wsName + "." + method + "." + formatDefault + ".ftl");
			} catch (IOException e) {
				throw new IllegalStateException(e);
			}
		}
		
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", "webscript" + wsFolder.replace("/", ".") + "." + wsName + "." + method);
		springContextXml.writeAttribute("parent", generateWebScript.beanParent());
		springContextXml.writeAttribute("class", className.toString());
		springContextXml.writeEndElement(); // bean
	}

	private void processService(Element annotatedClassElement) throws XMLStreamException {
		GenerateService generateService = annotatedClassElement.getAnnotation(GenerateService.class);
		Name className = ((TypeElement) annotatedClassElement).getQualifiedName();

		String serviceName = generateService.id();
		if (serviceName.isEmpty()) {
			serviceName = className.toString();
		}
		
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", serviceName);
		springContextXml.writeAttribute("class", className.toString());
		if (generateService.dependsOn().length > 0) {
			springContextXml.writeAttribute("depends-on", String.join(", ", generateService.dependsOn()));
		}
		springContextXml.writeEndElement(); // bean
	}

	private void processBootstrapModel(Element annotatedClassElement) throws XMLStreamException {
		GenerateBootstrapModel generateBootstrapModel = annotatedClassElement.getAnnotation(GenerateBootstrapModel.class);
		Name className = ((TypeElement) annotatedClassElement).getQualifiedName();

		String modelName = generateBootstrapModel.id();
		if (modelName.isEmpty()) {
			modelName = className.toString();
		}
		
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", modelName);
		springContextXml.writeAttribute("parent", "dictionaryModelBootstrap");
		if (generateBootstrapModel.dependsOn().length > 0) {
			springContextXml.writeAttribute("depends-on", String.join(", ", generateBootstrapModel.dependsOn()));
		}
		if (generateBootstrapModel.importModels().length != 0) {
			springContextXml.writeStartElement("property");
			springContextXml.writeAttribute("name", "models");
			springContextXml.writeStartElement("list");
			for (String model : generateBootstrapModel.importModels()) {
				springContextXml.writeStartElement("value");
				springContextXml.writeCharacters(model);
				springContextXml.writeEndElement(); // value
			}
			springContextXml.writeEndElement(); // list
			springContextXml.writeEndElement(); // property
		}
		if (generateBootstrapModel.importLabels().length != 0) {
			springContextXml.writeStartElement("property");
			springContextXml.writeAttribute("name", "labels");
			springContextXml.writeStartElement("list");
			for (String label : generateBootstrapModel.importLabels()) {
				if (label.endsWith(".properties")) {
					label = label.substring(0, label.length() - ".properties".length());
				}
				springContextXml.writeStartElement("value");
				springContextXml.writeCharacters(label);
				springContextXml.writeEndElement(); // value
			}
			springContextXml.writeEndElement(); // list
			springContextXml.writeEndElement(); // property
		}
		springContextXml.writeEndElement(); // bean
		
		// https://docs.alfresco.com/content-services/latest/develop/repo-ext-points/bootstrap-content/
		int viewNumber = 1;
		for (BootstrapView view : generateBootstrapModel.importViews()) {
			springContextXml.writeStartElement("bean");
			String id = view.id();
			if (id.isEmpty()) {
				id = modelName + ".view" + viewNumber;
			}
			springContextXml.writeAttribute("id", id);
			viewNumber ++;
			
			springContextXml.writeAttribute("class", "org.alfresco.repo.admin.patch.impl.GenericBootstrapPatch");
			springContextXml.writeAttribute("parent", "basePatch");
			springContextXml.writeAttribute("depends-on", String.join(", ", view.dependsOn()));
			generateProperty(springContextXml, "id", id);
			generateProperty(springContextXml, "description", view.description());
			generateProperty(springContextXml, "fixesFromSchema", "0");
			generateProperty(springContextXml, "fixesToSchema", "${version.schema}");
			generateProperty(springContextXml, "targetSchema", "99999");
			springContextXml.writeStartElement("property");
			springContextXml.writeAttribute("name", "importerBootstrap");
			springContextXml.writeAttribute("ref", "spacesBootstrap");
			springContextXml.writeEndElement(); // property importerBootstrap
			generateProperty(springContextXml, "checkPath", view.checkPath());
			
			springContextXml.writeStartElement("property");
			springContextXml.writeAttribute("name", "bootstrapView");
			springContextXml.writeStartElement("props");
			generateProp(springContextXml, "uuidBinding", view.uuidBinding().name());
			generateProp(springContextXml, "path", view.path());
			generateProp(springContextXml, "location", view.location());
			
			springContextXml.writeEndElement(); // props 
			springContextXml.writeEndElement(); // property bootstrapView
			springContextXml.writeEndElement(); // bean
		}
	}

	private void processPatch(Element annotatedClassElement) throws XMLStreamException {
		GeneratePatch generatePatch = annotatedClassElement.getAnnotation(GeneratePatch.class);
		Name className = ((TypeElement) annotatedClassElement).getQualifiedName();

		String patchName = generatePatch.id();
		if (patchName.isEmpty()) {
			patchName = className.toString();
		}

		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", "patch." + patchName);
		springContextXml.writeAttribute("class", className.toString());
		springContextXml.writeAttribute("parent", "basePatch");
		if (generatePatch.dependsOn().length > 0) {
			springContextXml.writeAttribute("depends-on", String.join(", ", generatePatch.dependsOn()));
		}

		generateProperty(springContextXml, "id", "patch." + patchName);
		generateProperty(springContextXml, "description", "OWSI auto generate patch patch." + patchName);
		generateProperty(springContextXml, "fixesFromSchema", "0");
		generateProperty(springContextXml, "fixesToSchema", "${version.schema}");
		generateProperty(springContextXml, "targetSchema", "10000000");

		springContextXml.writeEndElement(); // bean
	}
	
	private void processScheduledJob(Element annotatedClassElement) throws XMLStreamException {
		GenerateCron generateCron = annotatedClassElement.getAnnotation(GenerateCron.class);
		String className = ((TypeElement) annotatedClassElement).getQualifiedName().toString();
		String serviceId = (generateCron.id().isEmpty()) ? className : "cron." + className;
		
		String startDelay = generateCron.startDelay();
		if (startDelay.startsWith("P")) {
			startDelay = Long.toString(Duration.parse(generateCron.startDelay()).get(ChronoUnit.SECONDS)*1000L);
		}
		
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", serviceId);
		springContextXml.writeAttribute("class", className.toString());
		if (generateCron.dependsOn().length > 0) {
			springContextXml.writeAttribute("depends-on", String.join(", ", generateCron.dependsOn()));
		}
		springContextXml.writeEndElement(); // bean
		
		String jobDetailId = serviceId + ".JobDetail";
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", jobDetailId);
		springContextXml.writeAttribute("class", "org.springframework.scheduling.quartz.JobDetailFactoryBean");
		generateProperty(springContextXml, "jobClass", "fr.openwide.alfresco.repo.core.cron.model.CronRunnableJob");
		springContextXml.writeStartElement("property");
		springContextXml.writeAttribute("name", "jobDataAsMap");
		springContextXml.writeStartElement("map");
		
		springContextXml.writeStartElement("entry");
		springContextXml.writeAttribute("key", "runnable");
		springContextXml.writeAttribute("value-ref", serviceId);
		springContextXml.writeEndElement(); // entry
		
		springContextXml.writeStartElement("entry");
		springContextXml.writeAttribute("key", "jobLockService");
		springContextXml.writeAttribute("value-ref", "jobLockService");
		springContextXml.writeEndElement(); // entry
		
		springContextXml.writeStartElement("entry");
		springContextXml.writeAttribute("key", "transactionService");
		springContextXml.writeAttribute("value-ref", "transactionService");
		springContextXml.writeEndElement(); // entry
		
		generateMapEntry(springContextXml, "logAsInfo", Boolean.toString(generateCron.logAsInfo()));
		generateMapEntry(springContextXml, "readOnly", Boolean.toString(generateCron.readOnly()));
		generateMapEntry(springContextXml, "enable", generateCron.enable());
		generateMapEntry(springContextXml, "runAs", generateCron.runAs());

		springContextXml.writeEndElement(); // map
		springContextXml.writeEndElement(); // property
		springContextXml.writeEndElement(); // bean
		
		String cronTriggerFactoryBeanId = serviceId + ".CronTriggerFactoryBean";
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", cronTriggerFactoryBeanId);
		springContextXml.writeAttribute("class", "org.springframework.scheduling.quartz.CronTriggerFactoryBean");
		springContextXml.writeStartElement("property");
		springContextXml.writeAttribute("name", "jobDetail");
		springContextXml.writeAttribute("ref", jobDetailId);
		springContextXml.writeEndElement(); // property
		generateProperty(springContextXml, "cronExpression", generateCron.cronExpression());
		generateProperty(springContextXml, "startDelay", startDelay);
		springContextXml.writeEndElement(); // bean
		
		springContextXml.writeStartElement("bean");
		springContextXml.writeAttribute("id", serviceId + ".customTriggersList");
		springContextXml.writeAttribute("class", "org.springframework.scheduling.quartz.SchedulerAccessorBean");
		springContextXml.writeStartElement("property");
		springContextXml.writeAttribute("name", "scheduler");
		springContextXml.writeAttribute("ref", "schedulerFactory");
		springContextXml.writeEndElement(); // property
		springContextXml.writeStartElement("property");
		springContextXml.writeAttribute("name", "triggers");
		springContextXml.writeStartElement("list");
		springContextXml.writeStartElement("ref");
		springContextXml.writeAttribute("bean", cronTriggerFactoryBeanId);
		springContextXml.writeEndElement(); // ref
		springContextXml.writeEndElement(); // list
		springContextXml.writeEndElement(); // property

		springContextXml.writeEndElement(); // bean
	}

	@FunctionalInterface
	private interface XmlGenerator {
		void generate(XMLStreamWriter xml) throws XMLStreamException;
	}
	
	private void generateXml(Element annotatedClassElement, String module, String name, XmlGenerator generator) {
		Filer filer = processingEnv.getFiler();
		try {
			FileObject springContextXml = filer.createResource(StandardLocation.CLASS_OUTPUT, 
					module, name, annotatedClassElement);
			try (Writer out = springContextXml.openWriter()) {
				XMLStreamWriter xml = new IndentingXMLStreamWriter(XMLOutputFactory.newFactory().createXMLStreamWriter(out));
				xml.writeStartDocument();
				xml.writeComment("Generated by " + getClass() + " for " + annotatedClassElement);
				
				generator.generate(xml);
				
				xml.writeEndDocument();
				xml.flush();
			}
			processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Le fichier " + springContextXml.toUri() + " a été généré");
		} catch (IOException e) {
			throw new IllegalStateException(e);
		} catch (XMLStreamException e) {
			throw new IllegalStateException(e);
		}
	}

	private void generateProperty(XMLStreamWriter xml, String propertyName, String propertyValue) throws XMLStreamException {
		xml.writeStartElement("property");
		xml.writeAttribute("name", propertyName);
		xml.writeAttribute("value", propertyValue);
		xml.writeEndElement(); // property
	}
	private void generateMapEntry(XMLStreamWriter xml, String key, String value) throws XMLStreamException {
		xml.writeStartElement("entry");
		xml.writeAttribute("key", key);
		xml.writeAttribute("value", value);
		xml.writeEndElement(); // entry
	}
	private void generateProp(XMLStreamWriter xml, String key, String value) throws XMLStreamException {
		xml.writeStartElement("prop");
		xml.writeAttribute("key", key);
		xml.writeCharacters(value);
		xml.writeEndElement(); // entry
	}

	private String getFullName(Element element) {
		Element parent = element.getEnclosingElement();
		return ((parent != null) ? parent + "." : "") + element.getSimpleName().toString();
	}

}
