<%@ taglib prefix="c"			uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="decorator"	uri="http://www.opensymphony.com/sitemesh/decorator" %>
<%@ taglib prefix="fn"			uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form"		uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt"			uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="sec"			uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="spring"		uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="alfapp"		uri="http://app.alfresco.openwide.fr/tags/util" %>
<%@ taglib prefix="owsi"		uri="http://app.alfresco.openwide.fr/tags/util" %>
